apiVersion: batch/v1
kind: CronJob
metadata:
  name: nasa-cron
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nasa-cron
            image: leewallen/curlit:1.0
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -c
            - date; curl http://yellow:30080/nasa
          restartPolicy: OnFailure
