apiVersion: batch/v1
kind: CronJob
metadata:
  name: nasa-cron
spec:
  schedule: "30 9 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nasa-cron
              image: leewallen/curlit:0.0.1
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - date; curl http://yellow:30080/nasa
          restartPolicy: OnFailure
